[package]
name = "hello-rocket"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = "1.0.130"
redis = "0.21.5"

[dependencies.rocket]
version = "0.5.0-rc.1"
features = ["json"]


